### PR TITLE
Add deterministic options

### PR DESCRIPTION
**Pull request by bglusman**
This is already actually released as our own gem, as I was in a hurry and wasn't sure if the project was active/if you'd want this feature, but it's being used in KY now and am happy to undo the name changes/bump the version and update ky to rely on random_username, but we want consistent user names...  sort of like gravatar or something :-)  LMK if you want me to fix up as a proper PR

### CODE REVIEW

**Comment by m1foley** [comment]
Thanks. This sounds like a feature that can be useful. Can I ask why you decided to add this feature?

**Comment by bglusman** [comment]
Sure, I wanted to version config/secret combinations in ky for kubernetes deployments, and wanted human friendly names... We calculate a Sha of something deterministically so changes will (almost) always change the word but no change well result in danger name(s)

**Comment by bglusman** [comment]
Er same names, sorry on mobile:-)

**Comment by m1foley** [comment]
I'd love to add this feature to the gem. Can you please:

1. Fix it up as a normal PR
2. Add tests
3. Consider refactoring so that `Random.new` isn't instantiated every time `get_item` is called. I'm not certain but it seems like an unnecessary allocation of resources. It looks like `sample(random: nil)` is the same as calling without arguments (source: [Rubinius Array#sample](https://github.com/rubinius/rubinius/blob/master/core/array.rb)) so a solution might even be removing the ` || Random.new` (though simply doing that would probably be too confusing to people reading the code).

**Comment by mdiebolt** [comment]
Closed due to inactivity.

**Pull request closed without merging**
